version: "3.8"

services:
  gemini-chat-bot:
    container_name: gemini-chat-bot
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ACCESS_PASSWORD=${ACCESS_PASSWORD}
    depends_on:
      - postgres
    command: sh -c "npm install --force && npx drizzle-kit push && npm run dev"
    stdin_open: true
    tty: true

  postgres:
    image: postgres:15-alpine
    container_name: gemini-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432" # ← local port 5433 maps to internal 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
